use itvedant;
create table student(s_id int primary key,name varchar(50),city varchar (50));
insert into student values(106,'rohan',32);
select * from student;
update student set city='kanpur' where s_id=102;
desc student;
alter table student add column age int;
update student set age=38 where s_id=105;
delete from student where s_id=103;
select * from student where age<20;
select * from student order by age;
select * from student where s_id=103;
select * from student order by age desc;
alter table students rename to student;
alter table student rename column place to city;
alter table student modify city varchar(50) default 'bangloru';
create table coaching(c_id int primary key,c_name varchar(50),phone int);
insert into coaching values(5,'css',7897531933);
alter table coaching modify phone varchar(50);
select * from coaching;
alter table student add column c_id int;
update student set c_id=5 where s_id=105;
alter table student add foreign key (c_id) references coaching(c_id);
desc coaching;
show create table student;
create table accounts(a_id int,a_type varchar(50),balance decimal(10,2));
create table transactions(t_id int,t_date int ,amount decimal(10,2),t_type varchar(50));
create table branches(b_id int,b_name varchar(50),b_address varchar(50),b_phone varchar(50));
create table accountbranches(assignmentdate date);
create table loans(l_id int,l_amount decimal(10,2),interestrate decimal(5,2),startdate date,enddate date);
create table customers(c_id int primary key,firstname varchar(50),lastname varchar(50),email varchar(50),phone varchar(50),accountcreationdate date);
alter table accounts add column c_id int;
alter table accounts add constraint foreign key(c_id) references customers(c_id);
alter table accounts add column b_id int;
alter table accounts add constraint foreign key(b_id) references branches(b_id);
alter table branches add primary key (b_id);
alter table accounts add primary key (a_id);
alter table transactions add column a_id int;
alter table transactions add constraint foreign key(a_id) references accounts(a_id);
alter table loans add column c_id int;
alter table loans add constraint foreign key(c_id) references customers(c_id);